Repository novnc/noVNC, pull requests merged in 2018-08, with the labels that each got.

#1118 Turn off view drag when scaling
  app/ui.js
Labels: bug, ui/full

#1117 Fix test playback
  tests/playback.js
  tests/vnc_playback.html
  utils/launch.sh
Labels: bug

#1129 Cleanup of vnc_lite.html
  app/styles/lite.css
  vnc_lite.html
Labels: ui/lite
