Repository novnc/noVNC, pull requests merged in 2020-02, with the labels that each got.

#1361 Correcting path to package.json for running at a path other than root.
  app/ui.js
Labels: bug, ui/full

#1374 Hide clipboard side bar button when view only mode
  app/ui.js
Labels: feature, ui/full

#1373 Add possibility to set quality ("JPEG Quality Level Pseudo-encoding")
  core/rfb.js
  core/util/polyfill.js
  docs/API.md
  tests/test.rfb.js
Labels: feature
