Repository novnc/noVNC, pull requests merged in 2020-06, with the labels that each got.

#1403 Properly limit mouse movement to once every 17 ms
  core/input/mouse.js
  core/rfb.js
  tests/test.mouse.js
  tests/test.rfb.js
Labels: bug, regression

#1411 Enforce camelCase
  .eslintrc
  app/ui.js
  app/webutil.js
  core/base64.js
  core/decoders/hextile.js
  core/decoders/raw.js
  core/deflator.js
  core/display.js
  core/inflator.js
  core/rfb.js
  core/util/logging.js
  core/websock.js
  tests/assertions.js
  tests/fake.websocket.js
  tests/playback-ui.js
  tests/playback.js
  tests/test.deflator.js
  tests/test.display.js
  tests/test.rfb.js
  tests/test.util.js
  tests/test.websock.js
  utils/genkeysymdef.js
  utils/use_require.js
  utils/use_require_helpers.js
Labels: cleanup

#1414 Add gesture handling
  .eslintrc
  app/images/mouse_left.svg
  app/images/mouse_middle.svg
  app/images/mouse_none.svg
  app/images/mouse_right.svg
  app/ui.js
  core/display.js
  core/input/gesturehandler.js
  core/input/mouse.js
  core/rfb.js
  core/util/cursor.js
  core/util/element.js
  docs/API-internal.md
  docs/API.md
  tests/test.gesturehandler.js
  tests/test.mouse.js
  tests/test.rfb.js
  vnc.html
Labels: feature

#1423 Use GitHub actions instead of Travis/Sauce Labs
  .github/workflows/deploy.yml
  .github/workflows/lint.yml
  .github/workflows/test.yml
  .travis.yml
  karma.conf.js
  package.json
Labels: infra
