Repository novnc/noVNC, pull requests merged in 2022-04, with the labels that each got.

#1590 Added support for Apple Remote Desktop authentication
  .eslintrc
  core/rfb.js
  core/util/bigint-mod-arith.js
  core/util/md5.js
  tests/test.rfb.js
Labels: feature

#1644 Remove bigint-mod-arith.js
  core/rfb.js
  core/util/bigint-mod-arith.js
Labels: cleanup

#1647 Update French translation
  po/fr.po
Labels: translation
